apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-frontend
  labels:
    app: courier-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: courier-frontend
  template:
    metadata:
      labels:
        app: courier-frontend
    spec:
      containers:
      - name: courier-frontend
        image: yuvrajkarekar/courier-frontend:latest # Make sure to build this image: docker build -t courier-frontend:latest ./Frontend/Courier-Service-Management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: courier-frontend-service
spec:
  selector:
    app: courier-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
