spring.application.name=CourierKaro
spring.datasource.url=jdbc:mysql://localhost:3306/courier_service2?createDatabaseIfNotExist=true
spring.datasource.username=D4-92670-Vipul
spring.datasource.password=manager

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



#spring.security.oauth2.client.registration.google.scope=openid,email,profile

# JWT Configuration - All should have same prefix
app.jwt.secret=courierservicemanagementd4mustbelongerthan256bitsfOorhs256algorithmsecurityrequirements
app.jwt.expiration=86400000
app.jwt.expiration-remember=604800000


#disable spring security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
